compileTestJava {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

configurations {
    testCompileClasspath {
        extendsFrom testAnnotationProcessor
    }
}

dependencies {
    testImplementation 'org.junit.platform:junit-platform-suite:1.10.2'
    testImplementation "org.springframework.boot:spring-boot-starter-test:${spring_version}"
    testImplementation 'org.springframework.security:spring-security-test:5.7.10'

    testCompileOnly "org.projectlombok:lombok:${lombok_version}"
    testAnnotationProcessor "org.projectlombok:lombok:${lombok_version}"
}

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    reports {
//        csv.required = true
        xml.required = true
    }
}