package ru.controllers;

public enum TypesConnect {
    MAIN, REQUESTS, AUTH, PROFILES, SETTINGS, TUTOR, NEWS, CONTACTS,
    HTEACHERS, ADMINS, STUDENTS, PARENTS, TEACHERS, SCHEDULE, DNEVNIK,
    PJOURNAL, PERIODS, TEST, JOURNAL

}
