app:
    jwtSecret: 'secret'
    jwtExpirationInMs: 3600000
spring:
    datasource:
        url: jdbc:h2:~/db_test
        username: sa
        password:
        driverClassName: org.h2.Driver
    h2.console:
        enabled: true
        path: /console_db/
    main:
        allow-bean-definition-overriding: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect

        #spring:
#    datasource:
#        url: jdbc:postgresql://localhost:5432/EJournal
#        username: postgres
#        password: root
#        driver-class-name: org.postgresql.Driver
#    jpa:
#        database: postgresql
#        database-platform: org.hibernate.dialect.PostgreSQLDialect

        hibernate.ddl-auto: create-drop
    mail:
        default-encoding: UTF-8
        host: smtp.mail.ru
        username: noooreplyejournal1@mail.ru
        password: rfCZvBQJpzAAHz2wy7ck
        debug: true
        port: 465
        properties.mail:
            transport.protocol: smtp
            smtp:
                auth: true
                ssl.enable: true