app:
    jwtSecret: 'secret'
    jwtExpirationInMs: 3600000
    debug: true
    test: true
    origins: http://localhost:3000, http://192.168.1.66:3000, https://ddudde.github.io, http://localhost:9001
spring:
    main:
        allow-bean-definition-overriding: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate.ddl-auto: create-drop
    mail:
        default-encoding: UTF-8
        debug: true